import Head from 'next/head'
import { Inter } from '@next/font/google'
import { LoginButton } from '@/components/atoms/loginButton'
import { useUser } from '@/hooks/useUser/useUser'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { user, isLoggedIn, isLoading, isMutating } = useUser()

  if (isMutating) return <h1>Guardando preferencias del usuario</h1>
  return (
    <>
      <Head>
        <title>IChoose</title>
        <meta name="description" content="Generated by  Maxi" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginButton />
    </>
  )
}
