import Head from 'next/head'
import { useUser } from '@/hooks/useUser/useUser'
import { ChatbotApp } from '@/components/molecules/chatBot'

export default function Home() {
  const { isMutating } = useUser()

  if (isMutating) return <h1>Guardando preferencias del usuario</h1>
  return (
    <>
      <Head>
        <title>IChoose</title>
        <meta name="description" content="Generated by  Maxi" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChatbotApp isPreference />
    </>
  )
}
